version: '3.8'

services:
  atlantis:
    build: .
    container_name: atlantis
    networks:
      - atlantis_atlantis_default
    ports:
      - "4141:4141"
    volumes: 
      - /etc/atlantis/github-app-key.pem:/etc/atlantis/github-app-key.pem
      - ./terraform:/terraform
      - ./atlantis.yaml:/atlantis.yaml
    command: 
      - server 
      - --gh-app-key-file=/etc/atlantis/github-app-key.pem
      - --gh-app-id=1157716
      - --repo-allowlist=github.com/angatupyry/spotify-playlist-terraform
      - --write-git-creds
    
  spotify-auth-proxy:
    image: ghcr.io/conradludgate/spotify-auth-proxy
    container_name: spotify-auth-proxy
    ports:
      - "27228:27228"
    env_file:
      - .env  
    restart: unless-stopped
    networks:
      - atlantis_atlantis_default

networks:
  atlantis_atlantis_default:
    driver: bridge